Develop
Herm20/SEVENGINE pull request #6
Opened 2019-03-29 15:11 UTC by Herm20

Develop is now stable and ready to merge to master

2019-03-29 15:24 UTC, pyrophone commented on Engine/Engine/Assets/FragmentShader.frag
>  	gl_FragColor = vec4(uvFs, 0, 1);
FYI, we might want to make an `out vec4 fragColor` instead using gl_FragColor, since it is depricated and, therefore, may not always work.

2019-03-29 15:26 UTC, pyrophone commented on Engine/Engine/Core/Application.cpp
> +//	assetMan->SaveAssetToFile("Log", name.string().c_str(), Logger::GetLog());
Just curious on why this is commented out. Is this code causing issues / crashes?

2019-03-29 15:30 UTC, pyrophone approved these changes
Everything seems fine overall, just left a few comments

2019-03-29 15:36 UTC, SirGeoffers requested changes

2019-03-29 15:36 UTC, SirGeoffers commented on Engine/Engine/Core/Renderer.cpp
> +	obj2 = new Mesh(am->GetMesh("sphere"), glm::vec3(5, 0, 0));
I don't have access to these models. (sphere, sword, teapot)  Can't test without them.

2019-04-01 16:03 UTC, SirGeoffers approved these changes

2019-04-01 16:03 UTC, merged